#!/bin/bash
set -xeuf -o pipefail

DEBIAN_DIR=/home/user/ros1_dependencies_sources/src/yaml-cpp/debian/debian
cd ${DEBIAN_DIR}/patches
for patch_file in $(cat series); do
    patch -N -d /home/user/ros1_dependencies_sources/src/yaml-cpp/yaml-cpp-release-0.5.2 -p1 < $patch_file
done
#
mkdir -p /home/user/ros1_dependencies_sources/build/yaml-cpp
cd /home/user/ros1_dependencies_sources/build/yaml-cpp
cmake \
  -DCMAKE_INSTALL_PREFIX=/opt/jsk/${INSTALL_ROOT}/ros1_dependencies \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SHARED_LIBS=ON \
  -DYAML_CPP_BUILD_TOOLS=ON \
  ../../src/yaml-cpp/yaml-cpp-release-0.5.2
make -j4 install
